// Isolated demo fixture helper for coordinator-owned native Browser acceptance.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {configureOwnedPerformanceEnvironment,projectId}=require('./common');configureOwnedPerformanceEnvironment();
const req=require('node:module').createRequire(path.resolve(__dirname,'../../functions/package.json'));
const {initializeApp,deleteApp}=req('firebase-admin/app');const {getFirestore,Timestamp}=req('firebase-admin/firestore');
const backup=path.resolve(__dirname,'../../../docs/coordinator/task-09-bazaar-catalog/evidence/09b-native-backup.json');
const encode=v=>v?.toMillis?{__timestamp:[v.seconds,v.nanoseconds]}:Array.isArray(v)?v.map(encode):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,encode(x)])):v;
const decode=v=>v?.__timestamp!==undefined?new Timestamp(...v.__timestamp):Array.isArray(v)?v.map(decode):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,decode(x)])):v;
(async()=>{const app=initializeApp({projectId},'task09b-native');const db=getFirestore(app);const uid='perf-player',itemId='item-0001',resources=db.doc(`users/${uid}/state/resources`),inventory=db.collection(`users/${uid}/inventory`);
 const edit=async item=>{const auth=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=emulator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'perf-dm@example.test',password:'PerfTest!123',returnSecureToken:true})});const token=(await auth.json()).idToken;if(!token)throw Error('Demo DM login failed');const response=await fetch(`http://127.0.0.1:5001/${projectId}/europe-west8/task09WriteCatalogItem`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({data:{itemId,item,action:'save',operationId:'task09b-native-'+crypto.randomUUID()}})});const body=await response.json();if(!response.ok)throw Error(JSON.stringify(body));return body;};
 try{const action=process.argv[2];if(action==='snapshot'){if(fs.existsSync(backup))throw Error('Backup already exists');const inv=await inventory.get();if(inv.size!==500)throw Error('Expected 500 inventory entries');fs.writeFileSync(backup,JSON.stringify({projectId,uid,itemId,resources:encode((await resources.get()).data()),item:encode((await db.doc('items/'+itemId).get()).data()),inventoryIds:inv.docs.map(d=>d.id),receiptIds:(await db.collection('user_operations').get()).docs.map(d=>d.id)},null,2));console.log(JSON.stringify({backup,inventory:500,itemId}));}
 else if(action==='hide'||action==='restore'){const saved=JSON.parse(fs.readFileSync(backup));if(saved.projectId!==projectId||saved.uid!==uid||saved.itemId!==itemId)throw Error('Backup scope mismatch');await edit(action==='hide'?{...decode(saved.item),visibility:'custom',allowed_users:['perf-dm']}:decode(saved.item));if(action==='restore'){const added=(await inventory.get()).docs.filter(d=>!saved.inventoryIds.includes(d.id));for(const d of added){if(!d.id.startsWith('purchase_'))throw Error('Unexpected inventory addition');const receipt=d.id.slice(9);if(saved.receiptIds.includes(receipt))throw Error('Receipt predates backup');await db.doc('user_operations/'+receipt).delete();await d.ref.delete();}await resources.set(decode(saved.resources));if((await inventory.get()).size!==500)throw Error('Inventory restoration mismatch');console.log(JSON.stringify({restored:true,removedInventory:added.map(d=>d.id),resources:encode((await resources.get()).data())}));}else console.log(JSON.stringify({hidden:itemId}));}
 else if(action==='state'){console.log(JSON.stringify({projectId,itemId,meta:(await db.doc('catalogControl/bazaar').get()).data(),inventory:(await inventory.get()).size,resources:encode((await resources.get()).data())},null,2));}else throw Error('Use snapshot|hide|restore|state');}finally{await deleteApp(app);}})().catch(e=>{console.error(e);process.exitCode=1;});
